
name: Publish on GitHub, CurseForge & Modrinth

on:
  push:
    branches:
      - "release"
  workflow_dispatch:

env:
  MINECRAFT_VERSION: 1.21.10
  JAVA_VERSION: 22
  VERSION: 0.3.3beta2+1.21.10
  RELEASE_NAME: 4DMC 0.3.3beta2 for Minecraft 1.21.10
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 22

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 677605
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: yRBTv029
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          changelog-file: CHANGELOG.md
          files: build/libs/4dmc-*[0123456789].*[0123456789].*[0123456789]?(.jar|alpha|beta)

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

